// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColorCoder
{
    static class Vsix
    {
        public const string Id = "c60146c8-c6f8-40c7-95e7-a50ccdcf6223";
        public const string Name = "Color Coder";
        public const string Description = @"Provides the ability to change the color of important programming constructs in C# and VB.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Hamid Mosalla";
        public const string Tags = "syntax highlighter, colors, coloring, tagging";
    }
}
